# Generated by Django 3.2.9 on 2021-11-16 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_location_test_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('serviceID', models.SmallAutoField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('is_FI_req', models.BooleanField(default=False, verbose_name='FI Require')),
                ('FI_freq', models.CharField(max_length=20)),
                ('standardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.test_standard')),
            ],
        ),
    ]
