# Generated by Django 3.2.9 on 2021-11-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_seq',
            fields=[
                ('seqID', models.IntegerField(primary_key=True, serialize=False)),
                ('seqname', models.CharField(max_length=20)),
            ],
        ),
    ]
