# Generated by Django 3.2.9 on 2021-11-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('modelnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=20)),
                ('celltechnology', models.CharField(max_length=20)),
                ('cellmanufacturer', models.CharField(max_length=20)),
                ('numofcells', models.IntegerField()),
                ('numofcellsinser', models.IntegerField()),
                ('numofcellstr', models.IntegerField()),
                ('numofdio', models.IntegerField()),
                ('productlength', models.CharField(max_length=20)),
                ('productwidth', models.CharField(max_length=20)),
                ('productweight', models.CharField(max_length=20)),
                ('superstatetype', models.CharField(max_length=20)),
                ('superstatemanu', models.CharField(max_length=20)),
                ('substratetype', models.CharField(max_length=20)),
                ('substratemanu', models.CharField(max_length=20)),
                ('frametype', models.CharField(max_length=20)),
                ('frameadhe', models.CharField(max_length=20)),
                ('encaptype', models.CharField(max_length=20)),
                ('encapmanu', models.CharField(max_length=20)),
                ('junctboxtype', models.CharField(max_length=20)),
                ('junctboxmanu', models.CharField(max_length=20)),
            ],
        ),
    ]
