# Generated by Django 3.2.9 on 2021-11-16 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_test_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='perform_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsysvol', models.CharField(max_length=20)),
                ('voc', models.CharField(max_length=20)),
                ('isc', models.CharField(max_length=20)),
                ('vmp', models.CharField(max_length=20)),
                ('imp', models.CharField(max_length=20)),
                ('pmp', models.CharField(max_length=20)),
                ('ft', models.CharField(max_length=20)),
                ('modelnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('seqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.test_seq')),
            ],
        ),
    ]
